services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      OLLAMA_IGPU_ENABLE: '1'
      HSA_OVERRIDE_GFX_VERSION: 11.5.1
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
